name: PictureLogin
main: me.itsnathang.picturelogin.PictureLogin
api-version: 1.19
author: NathanG, _NickV
description: Display a cool login message with a picture of the player's skin.

version: ${version}
softdepend: [AuthMe, PlaceholderAPI]

commands:
  picturelogin:
    description: Picture Login command.
permisions:
  picturelogin.main:
    default: op
    description: Allows you to use /picturelogin
  picturelogin.show:
    default: op
    description: Allows message to be shown
    